config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'search/index'
  get 'reports/index'
  get 'reports/create'
  get 'pages/home'
  get 'crawler/index'
  get 'pages/about'
  get '/search' => 'search#index'
  root 'pages#home'
  mount Sidekiq::Web => '/sidekiq'
  resources :reports, only: [:index, :create]
  resources :jobs
  resources :search, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
    include PgSearch
    pg_search_scope :search, :against => [:title]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crawler_controller.rb
class CrawlerController < ApplicationController
    #@result = nil
    
    def index
 
        url3 = "https://www.vagas.com.br/vagas-de-Programador"
        page3 = HTTParty.get(url3)
        CrawlerVagaJob.perform_now(page3)
        CrawlerVagaService.new(page3).call

         
        url2 = "https://empregos.profissionaisti.com.br/?s=Programador"
        page2 = HTTParty.get(url2)
        CrawlerProfissionaisJob.perform_now(page2)
        CrawlerProfissionaisService.new(page2).call


        url = "https://www.empregos.com.br/vagas/programador"
        page = HTTParty.get(url)
        CrawlerEmpregoJob.perform_now(page)
        CrawlerEmpregoService.new(page).call

    end


    
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_job, only: :show
	def index
		@jobs = Job.order(created_at: :desc).paginate(:page => params[:page], :per_page => 20)
	end
	def show
	end


	private
	
		def set_job
			@job = Job.find(params[:id])
		end
end

app/controllers/pages_controller.rb
require './spec/support/read_file_helper'
class PagesController < ApplicationController
  
  def home
    page = get_file_as_string("./spec/mocks/empregos.html")
    CrawlerEmpregoJob.perform_now(page)
  end

  def about
  end

end

app/controllers/result_searches_controller.rb
class ResultSearchesController < ApplicationController
  def index
      PgSearch.multisearch(params[:query])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
      if params[:query].present?
        @jobs = Job.search(params[:query]).paginate(:page => params[:page], :per_page => 20)
      else
        @jobs = Job.order(created_at: :desc).paginate(:page => params[:page], :per_page => 20)
      end
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
     and (return if performed?)
    search = PgSearch.multisearch(params[:value]).order("created_at DESC")
    render json: Job.new(search.map(&:searchable)).serialized_json
  end

  

  private

    def check_search_value
      if params[:value].present? && params[:value].length < 3
        render json: { errors: "Parameter :value must have at least 3 characters" }
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%=render "shared/navbar" %>
<section id="search-index" class="valign-wrapper grey-text text-lighten-3">
	<div class="container">
		<div class= "row">
			<h1 class="light">SearchJobs!</h1>
			<p class="uppercased">Encontre seu job perfeito...</p>


  <nav class="grey lighten-2">
    <div class="nav-wrapper">
      <form>
        <div class="input-field">
          <input placeholder="Digite a sua cidade..." id="search" type="search" required>
          <label class="label-icon" for="search"><i class="material-icons indigo-text">search</i></label>
          <i class="material-icons indigo-text">close</i>
        </div>
        <div class="row right">
	        <%= link_to "Busca avançada..." %>
        </div>
        	

      </form>
    </div>
  </nav>



		</div>
	</div>
	
</section>


<div class="container">
	<div class= "row">
		
		
		<p class="grey-text text-darken-3">SearchJobs é um app de busca de vagas de trabalho para desenvolvedores Rails</p>
	</div>
</div>

app/views/jobs/index.html.erb
<section id="search-results">
	<div class="container">
		<div class= "row">
			<h4 class="light">Sua busca retornou <%=@jobs.count %> vagas</h4>
		</div>
		<div class="row">
			<% @jobs.each do |job| %>
				<div class="col s12 m6">
					<div class="card grey lighten-2 hoverable">
						<div class="card-content grey-text text-darken-2">
							<span class="card-title"><%=job.title %></span>
							<p class="light"><%=truncate(job.description, length: 100) %></p>
							<p>Empresa: <%=job.company %>, <%=job.location %></p>
						</div>
						<div class="card-action">
							<%= link_to "Saiba mais...", job_path(job) %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<div class="row center">
			
			<%= will_paginate @posts, renderer: MaterializePagination::Rails  %>
		</div>
	</div>
</section>

app/views/jobs/show.html.erb
<section id="job-show">
	<div class="container">
		<div class= "row">
			<div class="col s10 offset-s1 m8 offset-m2">
				
					
				<div class="card grey lighten-3 grey-text text-darken-2">
					<div class="card-content">
						<span class="card-title"><%=@job.title %> </span>
						<p class="light"><%=@job.description %></p>
						<p class="light"><strong>Empresa: </strong><%=@job.company %></p>
						<p class="light"><strong>Cidade: </strong><%=@job.location %></p>
						<p class="light"><strong>Publicada em: </strong><%=@job.published_at %></p>
						<p class="light"><strong>WebSite: </strong><%=link_to @job.url, @job.url %></p>
					</div>
					<div class="card-action">
						<%=link_to "Visite o site" %>
						<%=link_to "nova busca", root_path, class: "right" %>
					</div>
				</div>
				
					
				
			</div>	
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevOneBitCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render "shared/navbar" %>
    <%= yield %>
    <%=render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<section id="search-index" class="valign-wrapper grey-text text-lighten-3">
	<div class="container">
		<div class= "row">
			<h3 class="light">SearchJob!</h3>
			<!-- <p class="uppercased light">Encontre seu job perfeito...</p> -->
		</div>
		<div class="row">
			<nav class="grey lighten-2">
				<div class="nav-wrapper">
	
					<%= form_tag search_index_path, method: :get do %>
                        <%= text_field_tag :query, params[:query]  %>
                        <%= submit_tag "Search", name: nil, style: "display:none" %>
                    <% end %>
				</div>
			</nav>
		</div>
		<div class="row center">
			<h5 class="light">Encontre as melhores vagas de trabalho para desenvolvedores Ruby on Rails</h5>
		</div>
	</div>
</section>

app/views/pages/result.html.erb
<ul>
<% @pg_search_documents.each do |pg_search_document| %>
  <li><%= link_to pg_search_document.searchable.title, "../#{pg_search_document.searchable.class}/#{pg_search_document.searchable.id}" %></li>
<% end %>
</ul>

app/views/reports/create.html.erb
<h1>Reports#create</h1>
<p>Find me in app/views/reports/create.html.erb</p>

app/views/reports/index.html.erb
<% if flash[:notice] %>
  <b style="color: green"><%= flash[:notice] %></b>
<% end %>

<h3>Relatórios</h3>

<% @reports.each do |report| %>
  <%= link_to(report.split('/').last, "/reports/#{report.split('/').last}", target: "_blank") %>
  <br>
<% end %>

<hr>

<%= form_tag("/reports", method: "post") do %>
  <%= submit_tag("Gerar Novo") %>
<% end %>

app/views/search/index.html.erb
<section id="search-results">
	<div class="container">
		<div class= "row">
			<h4 class="light">Sua busca retornou <%=@jobs.count %> vagas</h4>
		</div>
		<div class="row">
			<% @jobs.each do |job| %>
				<div class="col s12 m6">
					<div class="card grey lighten-2 hoverable">
						<div class="card-content grey-text text-darken-2">
							<span class="card-title"><%=job.title %></span>
							<p class="light"><%=truncate(job.description, length: 100) %></p>
							<p>Empresa: <%=job.company %>, <%=job.location %></p>
						</div>
						<div class="card-action">
							<%= link_to "Saiba mais...", job_path(job) %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<div class="row center">
			
			<%= will_paginate @jobs, renderer: MaterializePagination::Rails  %>
		</div>
	</div>
</section>

app/views/shared/_footer.html.erb
<footer class="grey darken-1">
	<div class="container light">
		<div class="row grey-text text-lighten-3">
			<div class="col s6">
				<div class="">
					
					<!-- Time buscaJobs_4 -->
				</div>
			</div>	
			<div class="col s6">
				<div class="right">
					© <%= Time.current.year %> SearchJob
				</div>
					
			</div>				
		</div>
	</div>
</footer>

app/views/shared/_navbar.html.erb
  <nav class="grey lighten-3">
    <div class="container">
      <div class="nav-wrapper">
        <span><i class="material-icons left indigo-text">search</i><%=link_to "SearchJob", root_path, class: "brand-logo indigo-text light"%></span>
        
          
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a class="light" href="#">Busca avançada</a></li>
          <li><%= link_to "Sobre", pages_about_path, class: "light" %></li>

        </ul>
      </div>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="#">Busca avançada</a></li>
    <li><a href="#">Sobre</a></li>

  </ul>
          
<script>


  $(document).ready(function(){
    $('.sidenav').sidenav();
  });
</script>